/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "detail-page_actress": () => import("@/views/_builtin/detail-page/actress/index.vue"),
  "detail-page_category": () => import("@/views/_builtin/detail-page/category/index.vue"),
  "detail-page_video-list": () => import("@/views/_builtin/detail-page/video-list/index.vue"),
  "detail-page_video-player": () => import("@/views/_builtin/detail-page/video-player/index.vue"),
  "detail-page_video": () => import("@/views/_builtin/detail-page/video/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admin_user: () => import("@/views/admin/user/index.vue"),
  category_actress: () => import("@/views/category/actress/index.vue"),
  category_series: () => import("@/views/category/series/index.vue"),
  category_studio: () => import("@/views/category/studio/index.vue"),
  favorites: () => import("@/views/favorites/index.vue"),
  home: () => import("@/views/home/index.vue"),
  library: () => import("@/views/library/index.vue"),
};
