/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'solar:settings-minimalistic-linear',
      order: 999,
      hideInMenu: true
    },
    children: [
      {
        name: 'admin_user',
        path: '/admin/user',
        component: 'view.admin_user',
        meta: {
          title: 'admin_user',
          i18nKey: 'route.admin_user',
          icon: 'solar:user-linear'
        }
      }
    ]
  },
  {
    name: 'category',
    path: '/category',
    component: 'layout.base',
    meta: {
      title: 'category',
      icon: 'fluent-color:document-folder-24',
      i18nKey: 'route.category',
      order: 3
    },
    children: [
      {
        name: 'category_actress',
        path: '/category/actress',
        component: 'view.category_actress',
        meta: {
          title: 'category_actress',
          icon: 'fluent-color:people-24',
          i18nKey: 'route.category_actress'
        }
      },
      {
        name: 'category_series',
        path: '/category/series',
        component: 'view.category_series',
        meta: {
          title: 'category_series',
          icon: 'fluent-color:library-24',
          i18nKey: 'route.category_series'
        }
      },
      {
        name: 'category_studio',
        path: '/category/studio',
        component: 'view.category_studio',
        meta: {
          title: 'category_studio',
          icon: 'fluent-color:building-multiple-24',
          i18nKey: 'route.category_studio'
        }
      }
    ]
  },
  {
    name: 'detail-page',
    path: '/detail-page',
    component: 'layout.base',
    meta: {
      title: 'detail-page',
      hideInMenu: true,
      i18nKey: 'route.detail-page'
    },
    children: [
      {
        name: 'detail-page_actress',
        path: '/detail-page/actress',
        component: 'view.detail-page_actress',
        meta: {
          title: 'detail-page_actress',
          i18nKey: 'route.detail-page_actress'
        }
      },
      {
        name: 'detail-page_category',
        path: '/detail-page/category',
        component: 'view.detail-page_category',
        meta: {
          title: 'detail-page_category',
          i18nKey: 'route.detail-page_category'
        }
      },
      {
        name: 'detail-page_video',
        path: '/detail-page/video',
        component: 'view.detail-page_video',
        meta: {
          title: 'detail-page_video',
          i18nKey: 'route.detail-page_video'
        }
      },
      {
        name: 'detail-page_video-list',
        path: '/detail-page/video-list',
        component: 'view.detail-page_video-list',
        meta: {
          title: 'detail-page_video-list',
          i18nKey: 'route.detail-page_video-list'
        }
      },
      {
        name: 'detail-page_video-player',
        path: '/detail-page/video-player',
        component: 'view.detail-page_video-player',
        meta: {
          title: 'detail-page_video-player',
          i18nKey: 'route.detail-page_video-player'
        }
      }
    ]
  },
  {
    name: 'favorites',
    path: '/favorites',
    component: 'layout.base$view.favorites',
    meta: {
      title: 'favorites',
      icon: 'fluent-emoji:two-hearts',
      i18nKey: 'route.favorites',
      order: 3
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'fluent-color:poll-24',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'library',
    path: '/library',
    component: 'layout.base$view.library',
    meta: {
      title: 'library',
      icon: 'fluent-color:video-24',
      i18nKey: 'route.library',
      order: 2
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
